stages:
  - build
  - execute

compile_est_plan:
  stage: build
  script:
    echo "Building"
    module load toolchain/gompi/2020a devel/CMake numlib/FFTW
    rm -rf build && mkdir build && cd build
    cmake ..
    make
  artifacts:
    paths:
      build/openmp_many

run_est_plan:
  stage: execute
  script:
    ./openmp_many --num=16 --threads=2 --batch=2
