stages:
  - compile_estimate
  - execute_estimate
  - compile_measure
  - execute_measure

compile_fftw_est:
  stage: compile_estimate
  script:
    - cd fftw
    - make clean && make
  artifacts:
    paths:
    - fftw/bin/fftw

run_fftw_dp_est:
  stage: execute_estimate
  script:
    - cd fftw/bin
    - ./fftw -m 16 -n 16 -p 16 -i 5
  dependencies:
    - compile_fftw_est

run_fftw_sp_est:
  stage: execute_estimate
  script:
    - cd fftw/bin
    - ./fftw -m 16 -n 16 -p 16 -i 5 -s
  dependencies:
    - compile_fftw_est

compile_fftw_measure:
  stage: compile_measure
  script:
    - cd fftw
    - make clean && make MEASURE=1
  artifacts:
    paths:
    - fftw/bin/fftw

run_fftw_dp_measure:
  stage: execute_measure
  script:
    - cd fftw/bin
    - ./fftw -m 16 -n 16 -p 16 -i 5
  dependencies:
    - compile_fftw_measure

run_fftw_sp_est:
  stage: execute_measure
  script:
    - cd fftw/bin
    - ./fftw -m 16 -n 16 -p 16 -i 5 -s
  dependencies:
    - compile_fftw_measure