stages:
  - build
  - execute

compile_est_plan:
  stage: build
  script:
    echo "Building"
    module load toolchain/gompi/2020a devel/CMake numlib/FFTW
    rm -rf build && mkdir build && cd build
    cmake ..
    make

run_est_plan:
  stage: execute
  script:
    - mpirun -n 2 ./hybrid_many --num 64 --threads=5 --batch=2

compile_measure_plan:
  stage: build
  script:
    - make clean && make MEASURE=1

run_measure_plan:
  stage: execute
  script:
    - mpirun -n 2 ./hybrid_many --num 64 --threads=5 --batch=2