stages:
  - build
  - execute_openmp

compile_est_plan:
  stage: build
  script:
    - echo "Building"
    - module load toolchain/gompi devel/CMake numlib/FFTW
    - cd fftw
    - rm -rf build && mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - fftw/build/openmp_many

run_est_plan_openmp:
  stage: execute_openmp
  script:
    - cd fftw/build
    - ./openmp_many --num=16 --threads=2 --batch=2